name: Trigger Framework Tests

on:
  push:
    branches:
      - main  # or your main branch
    paths:
      - '**'  # adjust if needed to limit path scope

jobs:
  dispatch-framework:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Framework Repo via repository_dispatch
        run: |
          curl -X POST https://api.github.com/repos/AnupKSingh4u/Extent/dispatches \
          -H "Authorization: token ${{ secrets.FULLACCESSTOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{"event_type":"sut-updated"}'

